name: Build and deploy Node.js app to Azure Web App - assignment12

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        working-directory: Backend
        run: |
          npm install
          npm run build --if-present
          # npm run test --if-present  <-- removed test step

      - name: Zip Backend folder for deployment
        run: zip -r release.zip Backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2DB1B24D9B5045CC8E19B2B90DD6590D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1F19DA7B520B431F9727FE112521B243 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4EEF500A58EB40BD9A3BFE298ED27D30 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'assignment12'
          slot-name: 'Production'
          package: ./Backend
